#include "src/GameServer/TgGame/TgEffect/CheckEffectThreatModifier/TgEffect__CheckEffectThreatModifier.hpp"
#include "src/GameServer/TgGame/_effect_core/OriginResolver.hpp"
#include "src/GameServer/TgGame/_effect_core/DeviceLookup.hpp"
#include "src/GameServer/Constants/TgProperties.h"
#include "src/GameServer/Utils/ObjectClassCache/ObjectClassCache.hpp"
#include "src/Utils/Logger/Logger.hpp"

// Reimplementation of TgEffect::CheckEffectThreatModifier — stripped stub at
// 0x10a6f280. Called from TgEffectDamage.uc:242 with fThreat (= the health the
// hit actually removed) just before AddThreat records it against the attacker
// on the victim's TgAIController. Scales that threat by the ATTACKER's buffed
// prop 421 Threat Modifier through the intact GetBuffedProperty formula —
// the same query shape as CheckEffectBuffModifier, on a fixed property.
//
// Prop 421 carriers in the data, all percentages, all inert against the stub
// until now (docs/claude/threat.md, 2026-08-06 investigation):
//   Decoy               -20% for 10s while firing (effect category 1601)
//   Assault Melee III   +50%  (gated to Assault Melee)
//   Super Tank          +15%  (ungated)
//   Recon Rifle Damage  -10%  (gated to Recon Rifles)
// A gated entry must only scale threat generated by its own weapon family;
// passing the origin-resolved device instance + class skill into the query is
// what lets GetBuffedProperty's match rule enforce that.

// TgPawn::GetBuffedProperty — intact native @ 0x109d7ff0.
typedef void(__fastcall* GetBuffedPropertyFn)(
	ATgPawn*, void*,
	unsigned char /*eRequestContext*/, int /*nPropId*/,
	int /*nReqCategoryCode*/, int /*nReqSkillId*/, int /*nReqDeviceInstId*/,
	int /*bUsePotencyModifier*/, float /*fBaseValue*/, float* /*fBuffedValue*/,
	void* /*Effect*/);
static const GetBuffedPropertyFn GetBuffedPropertyNative = (GetBuffedPropertyFn)0x109d7ff0;

// ConvertPropToPropList context 1 = BUFF_PAWN; its `case 420: emit(421)` row
// is the only route to the 421 buff entries. bUsePotencyModifier stays 0:
// potency (376) scales effect magnitudes, and the damage feeding fThreat was
// already potency-scaled upstream — adding it here would double-apply.
static constexpr unsigned char BUFF_PAWN = 1;

// The pawn whose Threat Modifier buffs apply is the ATTACKER: a pawn directly,
// or the deploying pawn behind a deployable. Same resolution as
// CheckEffectBuffModifier (class-name checks, no IsA).
static ATgPawn* ResolveSourcePawn(AActor* inst) {
	if (!inst) return nullptr;
	if (ObjectClassCache::ClassNameContains(inst, "TgPawn")) {
		return static_cast<ATgPawn*>(inst);
	}
	if (ObjectClassCache::ClassNameContains(inst, "Deployable")) {
		APawn* deployer = inst->Instigator;
		if (deployer && ObjectClassCache::ClassNameContains(deployer, "TgPawn")) {
			return static_cast<ATgPawn*>(deployer);
		}
	}
	return nullptr;
}

void __fastcall TgEffect__CheckEffectThreatModifier::Call(UTgEffect* effect, void* /*edx*/, float* NewValue) {
	if (!effect || !NewValue) return;
	UTgEffectGroup* g = effect->m_EffectGroup;
	if (!g) return;

	const float origValue = *NewValue;
	if (origValue == 0.0f) return;  // no threat to scale

	ATgPawn* srcPawn = ResolveSourcePawn(g->m_Instigator);
	if (!srcPawn) return;

	OriginResolver::DeviceOrigin origin = OriginResolver::Resolve(g);
	int queryDevInst  = origin.instId;
	int queryCatSkill = origin.skillId;
	if (queryCatSkill == 0 && queryDevInst != 0) {
		queryCatSkill = DeviceLookup::SkillIdForDevice(srcPawn, queryDevInst);
	}

	// Query prop 420 THREAT, not 421 directly: ConvertPropToPropList's
	// srcType-1 table has no 421 row (direct 421 → EMPTY prop list → no-op),
	// while `case 420: emit(421)` is the canonical expansion that reaches the
	// pawn's 421 Threat Modifier buff entries. Verified against the live
	// buff table 2026-08-06: entries {421,cat=0,skill=0} +15 and
	// {421,cat=0,skill=366} +50 present, 421-direct query returned unchanged.
	float buffedValue = origValue;
	GetBuffedPropertyNative(
		srcPawn, /*edx=*/nullptr,
		BUFF_PAWN,
		GA_PROPERTY::TGPID_THREAT,
		/*nReqCategoryCode=*/g->m_nCategoryCode,
		/*nReqSkillId=*/queryCatSkill,
		/*nReqDeviceInstId=*/queryDevInst,
		/*bUsePotencyModifier=*/0,
		/*fBaseValue=*/origValue,
		/*fBuffedValue=*/&buffedValue,
		/*Effect=*/effect);

	if (buffedValue != origValue) {
		*NewValue = buffedValue;
		if (Logger::IsChannelEnabled("threat")) {
			Logger::Log("threat",
				"[THREAT-MOD] attacker=%p threat %.1f -> %.1f  egId=%d cat=%d devInst=%d skill=%d\n",
				srcPawn, origValue, buffedValue,
				g->m_nEffectGroupId, g->m_nCategoryCode,
				queryDevInst, queryCatSkill);
		}
	}
}
